services:
  postgres:
    image: postgres
    networks:
      - db
    environment:
      - POSTGRES_PASSWORD=abc1234
    dns:
      - 172.30.0.2
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    dns:
      - 172.30.0.3
    ports:
      - "8000:80"

networks:
  db:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
